### ISSUE TITLE
dx upload not working

### ISSUE THREAD

**Issue by RossDeVito** [lindgrengroup/hail-on-dnanexus#1]
Hi Barney,

Thanks for getting this together. I agree it's ridiculous you're tasked with maintaining DNANexus's stuff, so I feel a bit bad asking for more. 

I'm currently running a job that required using 'dx upload' to save the results at the end. When using the original dxjupyterlab app I can upload files from the worker to the project using either:
`dx upload some_data.txt` or `dx upload some_data.txt --path subdir_in_proj/`

When I run the same command with hail-on-dnanexus it looks like the files are instead getting uploaded to the directory given by 'dx pwd', which is not part of the project data. It's location is 'job-GPfbV2QJv7B2X5b4G91Kv0Qz-workspace:/' and I'm not sure how to change this to something in the project. 

Thanks for any help,
Ross

**Comment by barneyhill** [comment]
Hi Ross,
Thanks for the kind words, yes hopefully they sort themselves out soon enough...
I'm able to upload to the project by specifying path - Let me know if this works for you:
`dx upload file --path "project-{your-project-id}:/"`

Happy to help,
Barney

**Comment by RossDeVito** [comment]
Perfect, thanks.
